# Generated by Django 4.1.5 on 2023-01-31 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Direction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sigle", models.CharField(blank=True, max_length=10, null=True)),
                ("libelle", models.CharField(max_length=200)),
                ("create_at", models.DateField(auto_now_add=True)),
                ("modified_at", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="FriendWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50)),
                ("prenom", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50)),
                ("telephone", models.CharField(max_length=50)),
                ("adresse", models.CharField(max_length=50)),
                ("create_at", models.DateField(auto_now_add=True)),
                ("modified_at", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Unite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit", models.CharField(max_length=200)),
                ("libelle", models.CharField(max_length=200)),
                ("create_at", models.DateField(auto_now_add=True)),
                ("modified_at", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=200)),
                ("create_at", models.DateField(auto_now_add=True)),
                ("modified_at", models.DateField(auto_now_add=True)),
                (
                    "direction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.direction",
                        verbose_name="Direction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("create_at", models.DateField(auto_now_add=True)),
                ("modified_at", models.DateField(auto_now_add=True)),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.unite",
                        verbose_name="unité",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProducStoct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("create_at", models.DateField(auto_now_add=True)),
                ("modified_at", models.DateField(auto_now_add=True)),
                (
                    "pruduct",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.product",
                        verbose_name="produit",
                    ),
                ),
            ],
        ),
    ]
