# Generated by Django 4.1.5 on 2023-02-04 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0007_alter_product_options_producstoct_service_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producstoct",
            name="Service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="gestion.services",
                verbose_name="Services",
            ),
        ),
    ]
