# Generated by Django 4.1.5 on 2023-02-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0008_alter_producstoct_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producstoct",
            name="mouvement",
            field=models.CharField(
                choices=[("en", "Entrée"), ("out", "Sortie")], max_length=20
            ),
        ),
    ]
