# Generated by Django 4.1.5 on 2023-02-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0009_alter_producstoct_mouvement"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sec_stock",
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
