# Generated by Django 4.1.5 on 2023-02-04 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0010_product_sec_stock"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product", old_name="unit", new_name="unite",
        ),
    ]
