# Generated by Django 4.1.5 on 2023-02-04 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0011_rename_unit_product_unite"),
    ]

    operations = [
        migrations.RenameField(
            model_name="producstoct", old_name="Service", new_name="service",
        ),
        migrations.RemoveField(model_name="producstoct", name="mouvement",),
    ]
