# Generated by Django 4.1.5 on 2023-02-04 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0012_rename_service_producstoct_service_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendwork",
            name="service",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="gestion.services",
                verbose_name="Service",
            ),
            preserve_default=False,
        ),
    ]
