# Generated by Django 4.1.5 on 2023-02-05 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0013_friendwork_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producstoct",
            name="demandeur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gestion.friendwork",
                verbose_name="Demandeurs",
            ),
        ),
        migrations.AlterField(
            model_name="producstoct",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gestion.services",
                verbose_name="Services",
            ),
        ),
    ]
