# Generated by Django 4.1.5 on 2023-02-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0014_alter_producstoct_demandeur_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producstoct",
            name="mouvement",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
